format="$username$hostname$directory$git_branch$git_status$nodejs$cmd_duration$fill$memory_usage$localip$time$line_break$character"

[fill]
symbol = " "
style = ""

[username]
format = '[\[$user\]](bg:#b7bdf8 #181926)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[@$hostname ](bg:#b7bdf8 #181926)"
disabled = false

[directory]
format = "[ ğŸ“ $path ](bg:#c6a0f6 #181926)"

[git_branch]
symbol = "î‚ "
format = "[ $symbol $branch ](bg:#f5bde6 #181926)"

[git_status]
format = '([\[$all_status\]$ahead_behind ](bg:#f5bde6 #fe640b))'

[nodejs]
format = "[ $symbol$version ](bg:white #00ff00)"

[cmd_duration]
format = "[ â° $duration ](bg:#ee99a0 #181926)"

[memory_usage]
disabled = false
threshold = -1
symbol = " "
format = "[ $ram ](bg:#8bd5ca #181926)"

[localip]
ssh_only = false
format = "[ $localipv4 ](bg:#8aadf4 #181926)"
disabled = false

[time]
disabled = false
format = "[ ğŸ•“ $time ](bg:#5b6078 #cad3f5)"
